source 'https://cdn.cocoapods.org/'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name != 'Debug'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'NDEBUG']
      end
    end
  end
end


install! 'cocoapods', disable_input_output_paths: true
target 'VideoCapture' do
  platform :ios, '9.0'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'DbyPaas_iOS', path: '~/Projects/compare_agora/dby-paas-ios-sdk/DbyPaas_iOS.podspec'


end